baseurl = "https://moll.ninja/"
languageCode = "en-US"
title = "Miguel Moll"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profilepic.jpg"
  author = "Miguel Moll"
  description = "dsadfsDescribe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Link        = "https://miguel.moll.ninja"
  Github        = "MiguelMoll"
  Email         = "miguel AT moll DOT ninja"
  Twitter       = "radioact1ve"
  LinkedIn      = "miguelmoll"
